name: Check PR

on:
  pull_request:
    branches:
      '**'
  workflow_dispatch:

jobs:
  pr:
    env:
      KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
      KEYSTORE_KEY_ALIAS: ${{secrets.KEYSTORE_KEY_ALIAS}}
      KEYSTORE_KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
      KEYSTORE_STORE_PASSWORD: ${{secrets.KEYSTORE_STORE_PASSWORD}}
    
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Detekt
        run: ./gradlew detekt
        
#     - name: Tests
#       run: ./gradlew testDebugUnitTest

#     - name: Run Unit Tests
#       run: ./gradlew test
        
      - name: Build
        run: ./gradlew compileDebugKotlin
