name: CI

# Управление запуском рабочего процесса. 
# Триггерится по запросам push и pull в ветку master.
on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master, develop ]

  workflow_dispatch:
  
env:
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 KEYSTORE_FILE: $ {{ secrets.KEYSTORE_FILE }}
 KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
 KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
 KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

jobs:
 build:
  runs-on: ubuntu-latest
    
  steps:
   - name: Checkout
     uses: actions/checkout@v2  

   - name: Set up JDK 1.8
     uses: actions/setup-java@v1
     with:
      java-version: 1.8

   - name: Make Gradlew Executable
     run: chmod +x ./gradlew
   
   - name: Decode Keystore File
     id: decode_keystore_file
     uses: timheuer/base64-to-file@v1
     with:
      fileName: 'keystore_release.jks'
      encodedString: ${{ secrets.KEYSTORE_FILE }}
      
   - name: Set Decoded File Location as Environment
     run: echo "KEYSTORE_FILE_LOCATION=${{steps.decode_keystore_file.outputs.filePath}}" >> $GITHUB_ENV
        
   - name: Expose Version Name
     uses: michpohl/android-expose-version-name-action@v1.0.0
     with:
      path: app/build.gradle
      expose-version-name: 'true'
      expose-version-code: 'true'
      
#  - name: Run Unit Tests
#    run: ./gradlew test
      
   - name: Build Artifacts
     run: bash ./gradlew app:assembleDebug app:assembleRelease app:bundleRelease --stacktrace
        
#   - name: Build Artifacts
#     uses: eskatos/gradle-command-action@v1
#     with:
#      gradle-version: 6.7.1
#      wrapper-cache-enabled: true
#      dependencies-cache-enabled: true
#      configuration-cache-enabled: true
#      arguments: assembleDebug assembleRelease bundleRelease
        
   - name: Upload APKs to Outputs
     uses: actions/upload-artifact@v2
     with:
      path: |
       app/build/outputs/apk
       app/build/outputs/bundle
          
   - name: Create GitHub Release
     uses: softprops/action-gh-release@v1
     with:
      name: ${{ env.ANDROID_VERSION_NAME }}
      tag_name: ${{ env.ANDROID_VERSION_NAME }}
      draft: false
      prerelease: false
      files: |
       app/build/outputs/apk/**/*.apk
       app/build/outputs/bundle/**/*.aab
          
#  - name: Push Notification Message In Telegram
#    uses: appleboy/telegram-action@master
#    with:
#     to: ${{ secrets.TELEGRAM_BOT_ID }}
#     token: ${{ secrets.TELEGRAM_TOKEN }}
#     args: The ${{ github.event_name }} event triggered first step.
