name: CI

# Управление запуском рабочего процесса. 
# Триггерится по запросам push и pull в ветку master.
on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master, develop ]

  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_FILE: $ {{ secrets.KEYSTORE_FILE }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: DECODE KEYSTORE
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
         fileName: 'config/keystore.jks'
         encodedString: KEYSTORE_FILE
      
      - uses: actions/checkout@v2
      
      - name: SET UP JDK 1.8
        uses: actions/setup-java@v1
        with:
         java-version: 1.8
         
      - name: MAKE GRADLEW EXECUTABLE
        run: chmod +x ./gradlew
        
      # VersionName = env.ANDROID_VERSION_NAME, VersionCode = env.ANDROID_VERSION_CODE
      - name: EXPOSE VERSION NAME
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
         path: app/build.gradle
         expose-version-name: 'true'
         expose-version-code: 'true'
         
      - name: BUILD DEBUG APK
        run: ./gradlew app:assembleDebug
        
      - name: UPLOAD APKS TO OUTPUTS
        uses: actions/upload-artifact@v2
        with:
         name: Build Artifacts
         path: |
          app/build/outputs/apk
          app/build/outputs/bundle
          
      - name: CREATE GITHUB RELEASE
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.ANDROID_VERSION_NAME }}
          tag_name: ${{ env.ANDROID_VERSION_NAME }}
          draft: false
          prerelease: false
          files: app/build/outputs/apk/**/*.apk
          
#      - name: CREATE GITHUB RELEASE
#        id: create_release
#        uses: actions/create-release@v1
#        with:
#          tag_name: ${{ env.ANDROID_VERSION_NAME }}
#          release_name: ${{ env.ANDROID_VERSION_NAME }}
#          draft: false
#          prerelease: false
          
#      - name: CREATE GITHUB RELEASE
#        uses: marvinpinto/action-automatic-releases@latest
#        with:
#          repo_token: GITHUB_TOKEN
#          title: env.ANDROID_VERSION_NAME
#          automatic_release_tag: env.ANDROID_VERSION_NAME — не работает
#          draft: false
#          prerelease: false
#          files: |
#            *.apk
#            *.aab
          
#      - uses: eskatos/gradle-command-action@v1
#        with:
#         gradle-version: 6.7.1
#         wrapper-cache-enabled: true
#         dependencies-cache-enabled: true
#         configuration-cache-enabled: true
#         arguments: assembleRelease appDistributionUploadTemplateRelease
        
#      - name: Run Unit Tests
#        run: ./gradlew test
          
#      - name: Push Notification Message In Telegram
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_BOT_ID }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#          args: The ${{ github.event_name }} event triggered first step.
