name: Distribution App

on:
  push:
    branches: [ master ]
# pull_request:
#   branches: [ master ]

  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
  KEYSTORE_KEY_ALIAS: ${{secrets.KEYSTORE_KEY_ALIAS}}
  KEYSTORE_KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
  KEYSTORE_STORE_PASSWORD: ${{secrets.KEYSTORE_STORE_PASSWORD}}  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
      
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Decode Keystore File
        id: decode_keystore_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore_release.jks'
          encodedString: ${{secrets.KEYSTORE_FILE}}
          
      - name: Set Decoded File Location as Environment
        run: echo "KEYSTORE_FILE=${{steps.decode_keystore_file.outputs.filePath}}" >> $GITHUB_ENV
        
      - name: Expose Version Name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          path: app/build.gradle
          expose-version-name: 'true'
          expose-version-code: 'true'
          
#     - name: Build Debug Artifacts
#       run: bash ./gradlew app:assembleDebug
          
#     - name: Build Release Artifacts
#       run: bash ./gradlew app:assembleRelease --stacktrace
        
#     - name: Build Bundle Artifacts
#     - run: bash ./gradlew app:bundleRelease

#     - name: Upload Artifacts to Outputs
#       uses: actions/upload-artifact@v2
#       with:
#         path: |
#           app/build/outputs/apk
#           app/build/outputs/bundle
            
      # Download a build artifact that was previously uploaded in the workflow by the upload-artifact action
#     - name: Download a Build Artifact
#       uses: actions/download-artifact@v2
        
#     - name: Display structure of downloaded files
#       run: ls -R
        
#     - name: 'Echo download path'
#       run: echo ${{steps.download.outputs.download-path}}
            
#     - name: Create GitHub Release
#       uses: softprops/action-gh-release@v1
#       with:
#         name: ${{ env.ANDROID_VERSION_NAME }}
#         tag_name: ${{ env.ANDROID_VERSION_NAME }}
#         draft: false
#         prerelease: false
#         files: |
#           app/build/outputs/apk/**/*.apk
#           app/build/outputs/bundle/**/*.aab
          
#     - name: Distribute Artifacts via Firebase
#       run: bash ./gradlew appDistributionUploadRelease --stacktrace
#       env:
#         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

#      - name: Get Commits since last Release
#        id: changes
#        uses: simbo/changes-since-last-release-action@v1
#        with:
#          line-prefix: "• "
#          include-hashes: true

      - name: Check for new commits today
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1
        with:
          token: 'your_github_token'
          seconds: 86400 # One day in seconds
          branch: 'master'
      - name: Print something if new commits are found
        if: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' }}
        run: echo "You have ${{ steps.check-new-commits.outputs.new-commits-number }} new commit(s) ✅!"
      - name: Print another thing if new commits couldn't be found
        if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
        run: echo "You don't have new commits 🛑!"
          
      - name: Run Merge Commits
        uses: autamus/merge-commits@master
        with:
          repo_location: '/github/workspace/'

      - name: Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO_ID}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          disable_notification: false
          disable_web_page_preview: true
          document: app/build/outputs/apk/**/*.apk
          format: markdown
          message: |
            New Artifacts Available in [Repository](https://github.com/${{github.repository}})!
            Version: ${{env.ANDROID_VERSION_NAME}}(${{env.ANDROID_VERSION_CODE}})
            Changes since ${{steps.changes.outputs.last-tag}}:
            ${{steps.changes.outputs.log}}
            [See changes](https://github.com/${{github.repository}}/commit/${{github.sha}})
