# Create Release APKs

name: Production

on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.7.1
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleDebug assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: |
            app/build/outputs/apk
            app/build/outputs/bundle
